name: Run tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [8.0]

        steps:
            - uses: actions/checkout@v2
            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            - uses: php-actions/composer@v6
              with:
                  php_version: ${{ matrix.php }}
                  php_extensions:
                      - php8.0-cli
                      - php8.0-fpm
                      - php8.0-dev
                      - php8.0-xml
                      - php8.0-intl
                      - php8.0-mysql
                      - php8.0-mbstring
                      - php8.0-curl
                      - php8.0-apcu
                      - php8.0-xdebug
            - name: Display PHP version
              run: php -v
            - name: Run tests
              run: make test
