name: Run tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [8.0]

        steps:
            - uses: actions/checkout@v2
            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            - uses: php-actions/composer@v6
              with:
                  php_version: ${{ matrix.php }}
                  php_extensions: apcu
            - name: Display PHP version
              run: php -v
            - name: Configure recaptcha secrets
              run: cp config/recaptcha_secrets.json.dist config/recaptcha_secrets.json
            - name: Run tests
              run: make test
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            -   name: Cypress run
                uses: cypress-io/github-action@v4.x.x # use the explicit version number
                with:
                    build: npm run build
                    start: npm start