name: Run tests

on: [push, pull_request]

env:
    GEO_IP_DB_PATH: /home/runner/work/SecretSanta/SecretSanta/GeoLite2-City.mmdb
    DB_DATABASE: secretsanta
    DB_USER: secretsanta
    DB_PASSWORD: vagrant

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            - uses: php-actions/composer@v6
              with:
                  php_version: 8.0
                  php_extensions: apcu
            - name: Display PHP version
              run: php -v
            - name: Configure recaptcha secrets
              run: cp config/recaptcha_secrets.json.dist config/recaptcha_secrets.json
            - name: Install GeoLite IP DB
              run: curl https://www.secretsantaorganizer.com/GeoLite2-City.mmdb > /home/runner/work/SecretSanta/SecretSanta/GeoLite2-City.mmdb
            - name: Install Symfony binary
              run: curl -sS https://get.symfony.com/cli/installer | bash -s -- --install-dir=/usr/local/bin
            - name: Prepare empty database
              run: |
                  sudo /etc/init.d/mysql start
                  mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
            - name: Initialize application DB schema
              run: bin/console doctrine:schema:update --force
            - name: Run tests
              run: make test
            - name: Prepare Symfony local server TLS
              run: symfony server:ca:install
            - name: Run Cypress E2E tests
              uses: cypress-io/github-action@v4
              with:
                  config-file: cypress.config.github.js
                  build: npm run build
                  start: symfony server:start
            - uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
            - uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: cypress-videos
                  path: cypress/videos
